version: '3.8'

services:
  smartspendexpense:
    image: smartspendexpense
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/expensetracker?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootsmart
      SERVER_PORT: 8081
    networks:
      - app-network

  mysql:
    image: mysql:8.0.37
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootsmart
      MYSQL_DATABASE: expensetracker
    networks:
      - app-network

networks:
  app-network:
